<?php

declare(strict_types=1);

namespace Zephyrus\Data;

use PDO;
use PDOException;
use PDOStatement;
use Zephyrus\Core\Config\DatabaseConfig;

/**
 * Thin PDO wrapper that provides:
 *   - A clean construction path from DatabaseConfig or a pre-built PDO.
 *   - Uniform exception wrapping (DatabaseException instead of raw PDOException).
 *   - A transaction() helper that commits on success and rolls back on failure.
 *   - A query() helper that prepares + binds parameters and returns the statement.
 *
 * Testability: inject a pre-built PDO (e.g. sqlite::memory:) via the
 * constructor; use fromConfig() for production usage.
 */
final class Database
{
    public function __construct(private readonly PDO $pdo)
    {
        $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $this->pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    }

    /**
     * Build a Database instance by opening a MySQL/MariaDB connection described
     * by the given DatabaseConfig.
     *
     * @throws DatabaseException on PDO connection failure.
     */
    public static function fromConfig(DatabaseConfig $config): self
    {
        $dsn = sprintf(
            'mysql:host=%s;port=%d;dbname=%s;charset=%s',
            $config->host,
            $config->port,
            $config->database,
            $config->charset,
        );

        try {
            $pdo = new PDO($dsn, $config->username, $config->password, [
                PDO::ATTR_PERSISTENT => false,
                PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES {$config->charset}",
            ]);
        } catch (PDOException $e) {
            throw DatabaseException::connectionFailed($dsn, $e->getMessage());
        }

        return new self($pdo);
    }

    /**
     * Execute a prepared statement with positional or named placeholders.
     *
     * @param array<int|string, mixed> $params
     * @throws DatabaseException on prepare or execution failure.
     */
    public function query(string $sql, array $params = []): PDOStatement
    {
        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute($params);

            return $stmt;
        } catch (PDOException $e) {
            throw DatabaseException::queryFailed($sql, $e->getMessage());
        }
    }

    /**
     * Run $work inside a database transaction.
     *
     * Commits if $work returns without throwing, rolls back otherwise.
     * The return value of $work is forwarded to the caller.
     *
     * Nested calls re-use the existing transaction (no savepoints).
     *
     * @throws DatabaseException when the DB itself fails to begin/commit/rollback.
     * @throws \Throwable re-throws any exception thrown inside $work after rolling back.
     */
    public function transaction(callable $work): mixed
    {
        $ownTransaction = !$this->pdo->inTransaction();

        if ($ownTransaction) {
            try {
                $this->pdo->beginTransaction();
            } catch (PDOException $e) {
                throw DatabaseException::transactionFailed("begin: {$e->getMessage()}");
            }
        }

        try {
            $result = $work($this);

            if ($ownTransaction) {
                $this->pdo->commit();
            }

            return $result;
        } catch (\Throwable $e) {
            if ($ownTransaction && $this->pdo->inTransaction()) {
                try {
                    $this->pdo->rollBack();
                } catch (PDOException $rollbackEx) {
                    throw DatabaseException::transactionFailed(
                        "rollback after error: {$rollbackEx->getMessage()}"
                    );
                }
            }

            throw $e;
        }
    }

    /**
     * Return the last auto-increment ID generated by an INSERT.
     */
    public function lastInsertId(): string|false
    {
        return $this->pdo->lastInsertId();
    }

    /**
     * Expose the underlying PDO for advanced callers (e.g. schema migrations).
     * Prefer the typed helpers for normal query work.
     */
    public function pdo(): PDO
    {
        return $this->pdo;
    }
}
